export enum EMessages {
    EMPTY = "required",
    ONLY_NUMBER = "Only for numbers",
    PHONE_LENGTH = "Enter a valid phone number",
    EMAIL_INCORRECT = "Enter a valid Email",
    ZIP_CODE_INCORRECT = "Enter a valid ZipCode",
    YEAR_INCORRECT = "Enter a valid Year",
    LICENCE_PLATE_INCORRECT = "Enter a valid Licence Plate",
    PASSWORD_INCORRECT = "Enter a valid Password",
    PASSWORDS_INCORRECT = "Passwords do not match",
    CONTAINS_INVALID_VALUE = "Field is contain invalid value",
    AMOUNT_INCORRECT = "Enter a valid value",
    AMOUNT_INCORRECT_RANGE = "Value must be from 0 to 100",
    SERVICE_FEE_INCORRECT = "Service fee should be less than user billing rate",

    LIST_ACTIONS_DATE = "Enter a correct date",
    LIST_ACTIONS_DATES = "Enter a correct dates",
    PROMO_CODE_INCORRECT = "Enter a valid Promo Code",
    AMOUNT_VALUE_FORMAT_INCORRECT = "Enter a value format 00.00",
}
